name: Release App
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.1

      - name: Build and Release
        run: |
          yarn run release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
